vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'

    mappings:
        projet_fichiers:
            uri_prefix:         '%app.path.projet_fichiers%'
            upload_destination: '%kernel.project_dir%/public%app.path.projet_fichiers%'
            delete_on_remove:   false

